# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mi Fans Indonesia
author: admin
email: admin@mifans.web.id
description: Sumber kode terbuka milik Mi Forum Fans Indonesia
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mifansindonesia.github.cio" # the base hostname & protocol for your site
permalink: /:categories/:title.html
twitter_username: mifansindonesia
github_username:  mifansindonesia

# Build settings
markdown: kramdown
